costs/income/urls.py
from django.urls import path
from costs.income import views


urlpatterns = [
    path('create/', views.IncomeCreateView.as_view(), name='create'),
    path('creat_acc/', views.IncomeAccountCreateView.as_view(), name='create_acc'),
    path('<int:pk>/update/', views.IncomeUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.IncomeDeleteView.as_view(), name='delete'),
    path('', views.IndexIncomesView.as_view(), name='index')
]

costs/urls.py
from django.contrib import admin
from django.urls import path, include
from costs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexMainView.as_view(), name='main'),
    path('users/', include(('costs.users.urls', 'users'), namespace='users')),
    path('spending/', include(('costs.spending.urls', 'spending'), namespace='spending')),
    path('income/', include(('costs.income.urls', 'income'), namespace='income'))
]

costs/income/models.py
from django.db import models
from django.contrib.auth.models import User


class Income(models.Model):
    price = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='income')
    timestamp = models.DateField(auto_now_add=True)
    account = models.CharField(max_length=75, default=1)
    balance = models.IntegerField(default=0)
    goal_title = models.CharField(max_length=75, default=None, null=True)
    goal = models.PositiveIntegerField(default=None, null=True)

costs/income/forms.py
from django import forms
from costs.income import models
from costs.income.models import Income

class IncomeCreateForm(forms.ModelForm):
    price = forms.IntegerField(label='Сумма', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    account = forms.CharField(label='Название счёта', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))

    class Meta:
        model = Income
        fields = [
            'price',
            'account'
        ]

    def clean_price(self):
        price = self.cleaned_data['price']
        if price <= 0:
            raise forms.ValidationError("Сумма должна быть больше нуля.")
        return price


class IncomeAccountCreateForm(forms.ModelForm):
    account = forms.CharField(label='Название счёта', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    goal_title = forms.CharField(label='Цель накопления', required=False, widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    goal = forms.IntegerField(label='Сумма накопления', required=False, widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    class Meta:
        model = Income
        fields = [
            'account',
            'goal_title',
            'goal'
        ]

costs/income/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from costs.income.forms import *
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from costs.users.mixins import RightUserMixin
from costs.income.mixins import AuthorAccessMixin
from costs.income.models import *
from costs.spending.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from costs.income.filters import *
from datetime import date
from costs.income.func import *
from costs.spending.func import summarize as spending_sum
from costs.spending.filters import AccountsFilter as SpendingFilter


class IncomeCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Запись добавлена'
    template_name = 'income/create.html'
    form_class = IncomeCreateForm
    success_url = reverse_lazy('income:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class IncomeAccountCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Цель отредактирована'
    template_name = 'income/create_goal.html'
    form_class = IncomeAccountCreateForm
    success_url = reverse_lazy('income:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class IncomeUpdateView(AuthorAccessMixin, SuccessMessageMixin, UpdateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Запись изменена'
    template_name = 'income/update.html'
    form_class = IncomeCreateForm
    success_url = reverse_lazy('income:index')
    model = Income


class IncomeDeleteView(AuthorAccessMixin, SuccessMessageMixin, DeleteView):
    model = Income
    template_name = 'Income/delete.html'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('income:index')
    success_message = 'Запись удалена'


class IndexIncomesView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        filter1 = LeadEntriesFilter(request.GET, queryset=Income.objects.filter(author=request.user))
        d1 = prepare(filter1.qs)
        labels, data = list(d1.keys()), list(d1.values())

        filter2 = AccountsFilter(request.GET, queryset=Income.objects.filter(author=request.user))
        d2 = summarize(filter2.qs)

        filter3 = SpendingFilter(request.GET, queryset=Spending.objects.filter(author=request.user))
        d3 = spending_sum(filter3.qs)
        d = balances(d2, d3)

        filter4 = BalanceFilter(request.GET, queryset=Income.objects.filter(author=request.user))
        d4 = parser(filter4.qs, filter3.qs)

        return render(request, 'income/index.html', {'filter1': filter1, 'labels': labels,
                                                     'data': data, 'd': d, 'd1': d4})

templates/income/create.html
{% extends "base_create.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
<h1>
Создать доход
</h1>
{% endblock title %}

templates/income/create_goal.html
{% extends "base_create.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
<h1>
Добавить/изменить цель
</h1>
{% endblock title %}

templates/income/delete.html
{% extends "base_delete.html" %}


{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title_name %}
Удалить
{% endblock title_name %}

templates/income/index.html
{% extends "base.html" %}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<div style="background-color:rgb(164,219,232, 0.3);border:0 solid black; padding:1rem 2rem 2rem 2rem;margin-bottom:.5rem; border-radius: 4rem 4rem 0 0;">
<h1 class="h1 my-4" >
    Список доходов
</h1>
<a class="btn btn-primary mb-3" href="{% url "income:create" %}">Создать доход</a>
<a class="btn btn-primary mb-3" href="{% url "income:create_acc" %}">Создать/изменить цель</a>
<div style="border-radius:3rem; padding:1rem;" class="card">
  <div class="card-body">
<form method="get">
  {{ filter1.form.as_p }}
    <br>
  <input type="submit" value='Применить фильтр' class="btn btn-primary"/>
</form>
</div>
</div>
</div>

<div style="background-color:rgb(164,219,232, 0.3);border:0 solid black; padding:2rem; border-radius: 0 0 4rem 4rem;">
<table class="table">
    <thead>
      <tr>
        <th scope="col">Название счёта</th>
        <th scope="col">Сумма</th>
        <th scope="col">Дата добавления</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    {% for sp in filter1.qs %}
      <tr>
        <td>{{ sp.account }}</td>
        <td>{{ sp.price }}</td>
        <td>{{ sp.timestamp }}</td>
        <td>
            <a class="btn btn-warning" href="{% url 'income:update' pk=sp.id %}">Изменить</a>
            <a class="btn btn-danger" href="{% url 'income:delete' pk=sp.id %}">Удалить</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
<br>
<br>
<br>
<br>
{% if data %}
<div style="background-color:rgb(164,219,232, 0.3);border:0 solid black;padding:3rem;margin-bottom:.5rem; border-radius: 4rem 4rem 0 0;">
<h1>Диаграмма</h1>
<hr>
<br>
<br>
<div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>
</div>
<div style="background-color:rgb(164,219,232, 0.3);border:0 solid black;padding:3rem; border-radius: 0 0 4rem 4rem;">
<table class="table">
    <thead>
      <tr>
        <th scope="col">Название Счёта</th>
        <th scope="col">Цель</th>
        <th scope="col">Сумма Цели</th>
        <th scope="col">Баланс</th>
      </tr>
    </thead>
    <tbody>
    {% for acc_id, contents in d1.items %}
      <tr style>
        <td>{{ acc_id }}</td>
        <td>{{ contents.2 }}</td>
        <td>{{ contents.1 }}</td>
        {% if contents.1 %}
          {% if contents.0 >= contents.1 %}
            <td style="background-color:lightgreen; color:white; text-shadow: 1px 1px 1px black"><b>{{ contents.0 }} из {{ contents.1}}</b></td>
          {% else %}
          <td>{{ contents.0 }} из {{ contents.1}}</td>
          {% endif %}
        {% else %}
          <td>{{ contents.0 }}</td>
          {% endif %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
<h1>
    Информация о данном отрезке отстутствует
</h1>
{% endif %}
</div>


  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
          'rgb(255, 99, 132)',
          'rgb(54, 162, 235)',
          'rgb(255, 205, 86)',
          'rgb(158, 0, 0)',
          'rgb(189, 255, 0)',
          'rgb(6, 4, 255)',
          'rgb(6, 160, 95)'
          ],
          label: 'Costs'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };
</script>
{% endblock content %}

templates/income/update.html
{% extends "base_update.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
<h1>
Изменить сумму
</h1>
{% endblock title %}