costs/income/urls.py
from django.urls import path
from costs.income import views


urlpatterns = [
    path('create/', views.IncomeCreateView.as_view(), name='create'),
    path('creat_acc/', views.IncomeAccountCreateView.as_view(), name='create_acc'),
    path('<int:pk>/update/', views.IncomeUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.IncomeDeleteView.as_view(), name='delete'),
    path('', views.IndexIncomesView.as_view(), name='index')
]

costs/urls.py
from django.contrib import admin
from django.urls import path, include
from costs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexMainView.as_view(), name='main'),
    path('users/', include(('costs.users.urls', 'users'), namespace='users')),
    path('spending/', include(('costs.spending.urls', 'spending'), namespace='spending')),
    path('income/', include(('costs.income.urls', 'income'), namespace='income'))
]

costs/users/urls.py
from django.urls import path
from costs.users import views

urlpatterns = [path('login/', views.LoginPerson.as_view(), name='login'),
               path('create/', views.CreatePerson.as_view(), name='create'),
               path('logout/', views.logout_user, name='logout'),
               path('<int:pk>/update/', views.PersonUpdate.as_view(), name='update'),
               path('<int:pk>/delete/', views.PersonDelete.as_view(), name='delete'),
               path('<int:pk>/show/', views.PersonShowView.as_view(), name='show')]

templates/base.html
<html lang="ru" xmlns:spending="http://www.w3.org/1999/xhtml">
    <head>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Система учета финансов</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/pricing/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">



    <style>

    body{
        margin: 0;
        padding: 0;
        font-family: 'century gothic';
    }
    .btn{
        border-radius:15px;
    }
    .Name{
        font-size:2.5vw;
        color:04a6d9;
        font-weight:bold;
        text-shadow: 1px 1px 1px black;
    }

       nav a{
        font-size:1vw;
        font-weight:bold;
        transition:.15s;
        box-shadow: 1px 1px 1px 2px;
        border: 1px solid white;
        padding: 0.3vw 1vw .3vw 1vw;
        border-radius:3rem;
       }
       nav a:hover{
            background-color:04a6d9;
            border-color:04a6d9;
            color:white !important;
            box-shadow: 0 0 0 white;
            transform: skew(-3deg,3deg);
       }
       nav a:active{
        transform: skew(5deg,-5deg);
        transform:scale(0.85);
       }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    {% load static %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>
    

<div class="container py-3">
  <header>
    <div  class="d-flex flex-column flex-md-row align-items-center mb-4 pb-3 border-bottom border-4">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none" previewlistener="true">
        <span class="Name">Учёт финансов</i></span>
      </a>
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        {% if request.user.is_authenticated %}
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "spending:index" %}">Расходы</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "income:index" %}">Доходы</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "users:show" pk=request.user.id %}">{{ request.user.username }}</a>
        <a class="py-2 text-dark text-decoration-none" href="{% url "users:logout" %}">Выйти</a>
        {% else %}
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "users:create" %}">Регистрация</a>
        <a class="py-2 text-dark text-decoration-none" href="{% url "users:login" %}">Вход</a>
        {% endif %}
      </nav>
    </div>

    
  </header>
  <main>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</ul>
{% endif %}
    {% block content %}{% endblock content %}
  </main>

  <footer class="pt-4 my-md-5 pt-md-5">
  </footer>
</div>


    
  

</body></html>

templates/base_create.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
{% block title %}{% endblock title %}
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Создать</button></p>
</form>
{% endblock content %}

templates/base_delete.html
{% extends "base.html" %}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<h1 class="h1 my-4">
    {% block title_name %}{% endblock title_name %}
</h1>

<p>
    {% block description %}{% endblock description %}
</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-outline-danger" value="Удалить">
</form>
{% endblock content %}

templates/base_update.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
{% block title %}{% endblock title %}
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Изменить</button></p>
</form>
{% block delete %}{% endblock delete %}
{% endblock content %}

templates/main.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div class="text-left">
        <h1 style="border-radius:4rem 4rem 0 0; background-color:rgb(32, 178, 170, 0.2); margin-bottom:.3rem;padding:2rem;"><strong>Добро пожаловать в <i>Систему учета финансов!</i></strong></h1>
        <p style="font-size:2.5vh;background-color:rgb(32, 178, 170, 0.2);margin-bottom:.3rem; padding:2rem;">Эффективно управляйте своими доходами и расходами, отслеживайте бюджет и достигайте финансовых целей с помощью нашей удобной платформы.</p>

        <ul style="width:100%;font-size:2vh;background-color:rgb(32, 178, 170, 0.2);margin-bottom:.3rem; padding:2rem 2rem 2rem 6rem; text-align: left; display: inline-block;">
            <li><strong>Контроль расходов:</strong> Легко добавляйте траты и анализируйте, на что уходит ваш бюджет.</li>
            <li><strong>Аналитика и отчеты:</strong> Визуализируйте свои данные с помощью диаграмм для лучшего понимания.</li>
            <li><strong>Личные цели:</strong> Создавайте финансовые цели и отслеживайте их прогресс.</li>
        </ul>
        <p style="font-size:2.5vh;border-radius:0 0 4rem 4rem; background-color:rgb(32, 178, 170, 0.2);margin-bottom:.5rem; padding:2rem;">Начните уже сегодня и сделайте первый шаг к финансовой стабильности!</p></div>
<br>
<br>

{% if request.user.is_authenticated %}
<a type="button" style="border-radius:2rem 2rem 0 0; margin-bottom:0.2rem" class="w-100 btn btn-lg btn-primary" href='{% url "spending:index" %}'>Расходы</a>
<a type="button"  style="border-radius:0 0 2rem 2rem;" class="w-100 btn btn-lg btn-primary" href='{% url "income:index" %}'>Доходы</a>
{% endif %}
{% endblock content %}